[2025-02-20T11:32:53.499+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T11:32:53.504+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2025-02-20T10:26:44.438022+00:00 [queued]>
[2025-02-20T11:32:53.506+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2025-02-20T10:26:44.438022+00:00 [queued]>
[2025-02-20T11:32:53.507+0100] {taskinstance.py:2867} INFO - Starting attempt 4 of 6
[2025-02-20T11:32:53.512+0100] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-02-20 10:26:44.438022+00:00
[2025-02-20T11:32:53.515+0100] {standard_task_runner.py:72} INFO - Started process 11090 to run task
[2025-02-20T11:32:53.518+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag', 'first_task', 'manual__2025-02-20T10:26:44.438022+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/var/folders/d6/rl60yzz90jj_2v0s4gm257780000gn/T/tmp1xr5g58f']
[2025-02-20T11:32:53.519+0100] {standard_task_runner.py:105} INFO - Job 13: Subtask first_task
[2025-02-20T11:32:53.557+0100] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.first_task manual__2025-02-20T10:26:44.438022+00:00 [running]> on host ajlas-macbook-air.local
[2025-02-20T11:32:53.577+0100] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ajlakorman' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T10:26:44.438022+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T10:26:44.438022+00:00'
[2025-02-20T11:32:53.578+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-20T11:32:53.578+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-20T11:32:53.579+0100] {logging_mixin.py:190} INFO - Current task name:first_task state:running start_date:2025-02-20 10:32:53.504774+00:00
[2025-02-20T11:32:53.579+0100] {logging_mixin.py:190} INFO - Dag name:our_first_dag and current dag run status:running
[2025-02-20T11:32:53.579+0100] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-20T11:32:53.580+0100] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/d6/rl60yzz90jj_2v0s4gm257780000gn/T
[2025-02-20T11:32:53.580+0100] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'Hello World, this is the first task']
[2025-02-20T11:32:53.583+0100] {subprocess.py:99} INFO - Output:
[2025-02-20T11:32:53.589+0100] {subprocess.py:106} INFO - /bin/bash: Hello: command not found
[2025-02-20T11:32:53.589+0100] {subprocess.py:110} INFO - Command exited with return code 127
[2025-02-20T11:32:53.593+0100] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-02-20T11:32:53.597+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-20T11:32:53.597+0100] {logging_mixin.py:190} INFO - Task start:2025-02-20 10:32:53.504774+00:00 end:2025-02-20 10:32:53.596963+00:00 duration:0.092189
[2025-02-20T11:32:53.597+0100] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): first_task> dag:<DAG: our_first_dag> dagrun:<DagRun our_first_dag @ 2025-02-20 10:26:44.438022+00:00: manual__2025-02-20T10:26:44.438022+00:00, state:running, queued_at: 2025-02-20 10:26:44.450725+00:00. externally triggered: True>
[2025-02-20T11:32:53.597+0100] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2025-02-20T11:32:53.598+0100] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=first_task, run_id=manual__2025-02-20T10:26:44.438022+00:00, execution_date=20250220T102644, start_date=20250220T103253, end_date=20250220T103253
[2025-02-20T11:32:53.605+0100] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-20T11:32:53.605+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 11090)
Traceback (most recent call last):
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-02-20T11:32:53.624+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-20T11:32:53.633+0100] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-20T11:32:53.633+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
