[2025-02-20T17:30:15.189+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T17:30:15.198+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_example.extract_data scheduled__2024-05-12T00:00:00+00:00 [queued]>
[2025-02-20T17:30:15.201+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_example.extract_data scheduled__2024-05-12T00:00:00+00:00 [queued]>
[2025-02-20T17:30:15.201+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-20T17:30:15.207+0100] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data> on 2024-05-12 00:00:00+00:00
[2025-02-20T17:30:15.211+0100] {standard_task_runner.py:72} INFO - Started process 39450 to run task
[2025-02-20T17:30:15.218+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_example', 'extract_data', 'scheduled__2024-05-12T00:00:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/d6/rl60yzz90jj_2v0s4gm257780000gn/T/tmpxyjzd6af']
[2025-02-20T17:30:15.221+0100] {standard_task_runner.py:105} INFO - Job 139: Subtask extract_data
[2025-02-20T17:34:42.313+0100] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-20T17:34:42.314+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-20T17:34:42.317+0100] {process_utils.py:132} INFO - Sending 15 to group 39450. PIDs of all processes in the group: [39450]
[2025-02-20T17:34:42.317+0100] {process_utils.py:87} INFO - Sending the signal 15 to group 39450
[2025-02-20T17:34:42.321+0100] {process_utils.py:80} INFO - Process psutil.Process(pid=39450, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='17:30:15') (39450) terminated with exit code -15
