[2025-02-20T17:36:01.427+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T17:36:01.432+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_example.extract_data scheduled__2024-06-07T00:00:00+00:00 [queued]>
[2025-02-20T17:36:01.434+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_example.extract_data scheduled__2024-06-07T00:00:00+00:00 [queued]>
[2025-02-20T17:36:01.434+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-20T17:36:01.439+0100] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data> on 2024-06-07 00:00:00+00:00
[2025-02-20T17:36:01.442+0100] {standard_task_runner.py:72} INFO - Started process 40336 to run task
[2025-02-20T17:36:01.446+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_example', 'extract_data', 'scheduled__2024-06-07T00:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/d6/rl60yzz90jj_2v0s4gm257780000gn/T/tmpkxeef3m_']
[2025-02-20T17:36:01.447+0100] {standard_task_runner.py:105} INFO - Job 182: Subtask extract_data
[2025-02-20T17:36:01.466+0100] {task_command.py:467} INFO - Running <TaskInstance: etl_example.extract_data scheduled__2024-06-07T00:00:00+00:00 [running]> on host ajlas-macbook-air.local
[2025-02-20T17:36:01.492+0100] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ajlakorman' AIRFLOW_CTX_DAG_ID='etl_example' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-07T00:00:00+00:00'
[2025-02-20T17:36:01.492+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-20T17:36:01.493+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-20T17:36:01.493+0100] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2025-02-20 16:36:01.432406+00:00
[2025-02-20T17:36:01.493+0100] {logging_mixin.py:190} INFO - Dag name:etl_example and current dag run status:running
[2025-02-20T17:36:01.493+0100] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-20T17:36:01.524+0100] {python.py:240} INFO - Done. Returned value was:       rank  finalWorth  ... latitude_country longitude_country
0        1      211000  ...        46.227638          2.213749
1        2      180000  ...        37.090240        -95.712891
2        3      114000  ...        37.090240        -95.712891
3        4      107000  ...        37.090240        -95.712891
4        5      106000  ...        37.090240        -95.712891
...    ...         ...  ...              ...               ...
2635  2540        1000  ...        35.861660        104.195397
2636  2540        1000  ...        37.090240        -95.712891
2637  2540        1000  ...        35.861660        104.195397
2638  2540        1000  ...        35.861660        104.195397
2639  2540        1000  ...        12.879721        121.774017

[2640 rows x 35 columns]
[2025-02-20T17:36:01.551+0100] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 790, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3645, in xcom_push
    XCom.set(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/serialization/serde.py", line 149, in serialize
    data, serialized_classname, version, is_serialized = _serializers[qn].serialize(o)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/serialization/serializers/pandas.py", line 40, in serialize
    import pyarrow as pa
ModuleNotFoundError: No module named 'pyarrow'
[2025-02-20T17:36:01.556+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-20T17:36:01.556+0100] {logging_mixin.py:190} INFO - Task start:2025-02-20 16:36:01.432406+00:00 end:2025-02-20 16:36:01.555754+00:00 duration:0.123348
[2025-02-20T17:36:01.556+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data> dag:<DAG: etl_example> dagrun:<DagRun etl_example @ 2024-06-07 00:00:00+00:00: scheduled__2024-06-07T00:00:00+00:00, state:running, queued_at: 2025-02-20 16:36:00.198802+00:00. externally triggered: False>
[2025-02-20T17:36:01.556+0100] {logging_mixin.py:190} INFO - Failure caused by No module named 'pyarrow'
[2025-02-20T17:36:01.557+0100] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_example, task_id=extract_data, run_id=scheduled__2024-06-07T00:00:00+00:00, execution_date=20240607T000000, start_date=20250220T163601, end_date=20250220T163601
[2025-02-20T17:36:01.568+0100] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-20T17:36:01.569+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 182 for task extract_data (No module named 'pyarrow'; 40336)
Traceback (most recent call last):
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 790, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3645, in xcom_push
    XCom.set(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/serialization/serde.py", line 149, in serialize
    data, serialized_classname, version, is_serialized = _serializers[qn].serialize(o)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/serialization/serializers/pandas.py", line 40, in serialize
    import pyarrow as pa
ModuleNotFoundError: No module named 'pyarrow'
[2025-02-20T17:36:01.597+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-20T17:36:01.605+0100] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-20T17:36:01.605+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
